<?php


namespace App\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SaveWorksCommand extends Command
{
    protected static $defaultName = 'app:save-works';
    private $requirePass;

    public function __construct(bool $requirePass = false)
    {
        $this->requirePass = $requirePass;
        parent::__construct();
    }

    protected function configure()
    {
        $this->setDescription('Get all works');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        echo 'Hi!';exit();

        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}